import DashboardLayout from "@/components/DashboardLayout";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { trpc } from "@/lib/trpc";
import { CircleCheck, CircleSlash2, ShieldAlert } from "lucide-react";

export default function ReviewQueue() {
  const { data } = trpc.recovery.overview.useQuery();
  return <DashboardLayout><div className="mx-auto max-w-[1300px] space-y-6 pb-10"><section><p className="text-xs font-semibold uppercase tracking-[0.14em] text-slate-500">Merchant control center</p><h1 className="mt-1 text-3xl font-semibold tracking-tight text-slate-950">Review queue</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-600">High-value, low-confidence, and ambiguous recoveries never run unattended. They appear here with their evidence and stopping rules intact.</p></section><div className="grid gap-4 md:grid-cols-3"><QueueCard icon={ShieldAlert} label="Needs merchant approval" value="1" tone="amber" /><QueueCard icon={CircleCheck} label="Automatically progressing" value="1" tone="sky" /><QueueCard icon={CircleSlash2} label="Stopped safely" value="1" tone="slate" /></div><Card className="border-slate-200/80 shadow-sm"><CardHeader><CardTitle>Cases requiring attention</CardTitle></CardHeader><CardContent className="space-y-3">{data?.cases.filter(item => item.state === "APPROVAL_PENDING" || item.state === "EXCEPTION" || item.state === "STOPPED").map(item => <div key={item.id} className="rounded-2xl border border-slate-100 p-5"><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><div className="flex items-center gap-2"><p className="font-semibold text-slate-900">{item.id}</p><Badge variant="outline" className={item.state === "EXCEPTION" ? "border-rose-200 bg-rose-50 text-rose-700" : item.state === "STOPPED" ? "border-slate-200 bg-slate-50 text-slate-700" : "border-amber-200 bg-amber-50 text-amber-700"}>{item.state.replaceAll("_", " ")}</Badge></div><p className="mt-2 text-sm text-slate-600">{item.reason}</p><p className="mt-2 text-xs text-slate-400">{item.customer} · {item.updatedAt}</p></div><div className="text-left sm:text-right"><p className="text-xs uppercase tracking-wide text-slate-400">At-risk amount</p><p className="mt-1 text-lg font-semibold">₹{(item.amountPaise / 100).toLocaleString("en-IN")}</p></div></div></div>)}</CardContent></Card><p className="rounded-2xl border border-sky-100 bg-sky-50 p-4 text-sm text-sky-900">Razorpay Test Mode — Sandbox: queue examples are simulated and no real customer contact or money movement occurs.</p></div></DashboardLayout>;
}
function QueueCard({ icon: Icon, label, value, tone }: { icon: typeof ShieldAlert; label: string; value: string; tone: "amber" | "sky" | "slate" }) { const color = { amber: "bg-amber-50 text-amber-700", sky: "bg-sky-50 text-sky-700", slate: "bg-slate-100 text-slate-700" }[tone]; return <Card className="border-slate-200/80 shadow-sm"><CardContent className="flex items-center gap-4 p-5"><div className={`rounded-2xl p-3 ${color}`}><Icon className="h-5 w-5" /></div><div><p className="text-2xl font-semibold tracking-tight">{value}</p><p className="mt-1 text-sm text-slate-500">{label}</p></div></CardContent></Card>; }
